# Reasoning Scaling Laws

Training and benchmark pipeline testing H1 (data efficiency vs. model size) and H2 (agentic compute vs. model scale) on GSM8K.

**Run order:** Cell 0 (env vars) → Cell 1 (install, then **restart kernel**) → Cell 2 (verify imports) → Cell 3 (download from GitHub) → Cell 4 (mount Drive) → Cell 5 (GPU check) → Cell 6 (config) → then either the Test Run cell, or Train 3B / Train 7B → Verify → Benchmark → Results.

**Important:** after running the install cell you must restart the kernel (Runtime → Restart session) before continuing — numpy/torch have C extensions that cannot reload in a running kernel. Re-run Cell 0 after the restart so the env vars are set again.

The 3B and 7B training cells can be run in separate Colab sessions — checkpoints are saved to Drive after every epoch.

In [1]:
!rm -rf /content/unsloth_compiled_cache

In [ ]:
# Cell 0 — Environment setup. MUST run before any unsloth import.
import os

print("Env cell ran.")

In [2]:
# Cell 1 — Install dependencies
# 1. Avinstallera trasiga versioner först
!pip uninstall -y bitsandbytes unsloth unsloth_zoo vllm

# 2. Installera rätt version av bitsandbytes anpassad för CUDA 12
!pip install --no-cache-dir bitsandbytes --extra-index-url https://download.pytorch.org/whl/cu121

# 3. Installera Unsloth och dess vänner på rätt sätt
!pip install --no-cache-dir unsloth unsloth_zoo vllm datasets trl matplotlib

# >>> After this finishes, RESTART THE KERNEL, then re-run Cell 0, then run Cell 2. <<<

WARNING: Skipping bitsandbytes as it is not installed.
WARNING: Skipping unsloth as it is not installed.
WARNING: Skipping unsloth_zoo as it is not installed.
WARNING: Skipping vllm as it is not installed.
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu121
Collecting bitsandbytes
  Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: torch<3,>=2.3 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.11.0+cu128)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (2.0.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bitsandbytes) (26.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.29.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (4.15.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2025.3.0)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (12.9.6)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch<3,>=2.3->bitsandbytes) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.3->bitsandbytes) (12.8.90)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch<3,>=2.3->bitsandbytes) (1.5.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch<3,>=2.3->bitsandbytes) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch<3,>=2.3->bitsandbytes) (3.0.3)
Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl (60.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 164.0 MB/s eta 0:00:00a 0:00:01
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.49.2
Collecting unsloth
  Downloading unsloth-2026.5.8-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.8/57.8 kB 149.2 MB/s eta 0:00:00
Collecting unsloth_zoo
  Downloading unsloth_zoo-2026.5.4-py3-none-any.whl.metadata (33 kB)
Collecting vllm
  Downloading vllm-0.21.0-1-cp38-abi3-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Collecting trl
  Downloading trl-1.5.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: wheel>=0.42.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.47.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from unsloth) (26.2)
Collecting torch<2.11.0,>=2.4.0 (from unsloth)
  Downloading torch-2.10.0-3-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (31 kB)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.26.0+cu128)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from unsloth) (2.0.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from unsloth) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from unsloth) (5.9.5)
Collecting tyro (from unsloth)
  Downloading tyro-1.0.13-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from unsloth) (5.29.6)
Collecting xformers>=0.0.27.post2 (from unsloth)
  Downloading xformers-0.0.35-py39-none-manylinux_2_28_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: bitsandbytes!=0.46.0,!=0.48.0,>=0.45.5 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.49.2)
Requirement already satisfied: triton>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (3.6.0)
Requirement already satisfied: sentencepiece>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.2.1)
Collecting datasets
  Downloading datasets-4.3.0-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: accelerate>=0.34.1 in /usr/local/lib/python3.12/dist-packages (from unsloth) (1.13.0)
Requirement already satisfied: peft!=0.11.0,>=0.18.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.19.1)
Requirement already satisfied: huggingface_hub>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from unsloth) (1.16.1)
Collecting hf_transfer (from unsloth)
  Downloading hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: diffusers in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.37.1)
Collecting transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3 (from unsloth)
  Downloading transformers-5.5.0-py3-none-any.whl.metadata (32 kB)
Collecting trl
  Downloading trl-0.24.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from unsloth) (0.25.1)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (from unsloth) (2.12.3)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from unsloth) (6.0.3)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from unsloth) (1.6.0)
Collecting torchao>=0.13.0 (from unsloth_zoo)
  Downloading torchao-0.17.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (20 kB)
Collecting cut_cross_entropy (from unsloth_zoo)
  Downloading cut_cross_entropy-25.1.1-py3-none-any.whl.metadata (9.3 kB)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo) (11.3.0)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo) (2025.11.3)
Collecting msgspec (from unsloth_zoo)
  Downloading msgspec-0.21.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.8 kB)
Requirement already satisfied: typing_extensions in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo) (4.15.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from unsloth_zoo) (3.29.0)
Requirement already satisfied: cachetools in /usr/local/lib/python3.12/dist-packages (from vllm) (6.2.6)
Requirement already satisfied: requests>=2.26.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (2.32.4)
Collecting blake3 (from vllm)
  Downloading blake3-1.0.8-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.6 kB)
Requirement already satisfied: py-cpuinfo in /usr/local/lib/python3.12/dist-packages (from vllm) (9.0.0)
Collecting transformers!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,!=4.57.0,!=4.57.4,!=4.57.5,!=5.0.0,!=5.1.0,<=5.5.0,>=4.51.3 (from unsloth)
  Downloading transformers-4.57.6-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 266.8 MB/s eta 0:00:00
Requirement already satisfied: tokenizers>=0.21.1 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.22.2)
Requirement already satisfied: fastapi>=0.115.0 in /usr/local/lib/python3.12/dist-packages (from fastapi[standard]>=0.115.0->vllm) (0.136.1)
Requirement already satisfied: aiohttp>=3.13.3 in /usr/local/lib/python3.12/dist-packages (from vllm) (3.13.5)
Requirement already satisfied: openai>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (2.37.0)
Requirement already satisfied: prometheus_client>=0.18.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.25.0)
Collecting prometheus-fastapi-instrumentator>=7.0.0 (from vllm)
  Downloading prometheus_fastapi_instrumentator-7.1.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: tiktoken>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.13.0)
Collecting lm-format-enforcer==0.11.3 (from vllm)
  Downloading lm_format_enforcer-0.11.3-py3-none-any.whl.metadata (17 kB)
Collecting llguidance<1.4.0,>=1.3.0 (from vllm)
  Downloading llguidance-1.3.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)
Collecting outlines_core==0.2.14 (from vllm)
  Downloading outlines_core-0.2.14-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.6 kB)
Collecting diskcache==5.6.3 (from vllm)
  Downloading diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Collecting lark==1.2.2 (from vllm)
  Downloading lark-1.2.2-py3-none-any.whl.metadata (1.8 kB)
Collecting xgrammar<1.0.0,>=0.2.0 (from vllm)
  Downloading xgrammar-0.2.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.3 kB)
Collecting partial-json-parser (from vllm)
  Downloading partial_json_parser-0.2.1.1.post7-py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: pyzmq>=25.0.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (26.2.1)
Collecting gguf>=0.17.0 (from vllm)
  Downloading gguf-0.19.0-py3-none-any.whl.metadata (4.1 kB)
Collecting mistral_common>=1.11.2 (from mistral_common[image]>=1.11.2->vllm)
  Downloading mistral_common-1.11.2-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: opencv-python-headless>=4.13.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (4.13.0.92)
Requirement already satisfied: six>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (1.17.0)
Collecting setuptools<81.0.0,>=77.0.3 (from vllm)
  Downloading setuptools-80.10.2-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: einops in /usr/local/lib/python3.12/dist-packages (from vllm) (0.8.2)
Collecting compressed-tensors==0.15.0.1 (from vllm)
  Downloading compressed_tensors-0.15.0.1-py3-none-any.whl.metadata (4.7 kB)
Collecting depyf==0.20.0 (from vllm)
  Downloading depyf-0.20.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from vllm) (3.1.2)
Requirement already satisfied: watchfiles in /usr/local/lib/python3.12/dist-packages (from vllm) (1.2.0)
Requirement already satisfied: python-json-logger in /usr/local/lib/python3.12/dist-packages (from vllm) (4.1.0)
Collecting ninja (from vllm)
  Downloading ninja-1.13.0-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.1 kB)
Collecting pybase64 (from vllm)
  Downloading pybase64-1.4.3-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl.metadata (8.7 kB)
Collecting cbor2 (from vllm)
  Downloading cbor2-6.1.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Collecting ijson (from vllm)
  Downloading ijson-3.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (23 kB)
Collecting setproctitle (from vllm)
  Downloading setproctitle-1.3.7-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (10 kB)
Collecting openai-harmony>=0.0.3 (from vllm)
  Downloading openai_harmony-0.0.8-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.0 kB)
Collecting anthropic>=0.71.0 (from vllm)
  Downloading anthropic-0.104.1-py3-none-any.whl.metadata (3.2 kB)
Collecting model-hosting-container-standards<1.0.0,>=0.1.14 (from vllm)
  Downloading model_hosting_container_standards-0.1.15-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: mcp in /usr/local/lib/python3.12/dist-packages (from vllm) (1.27.1)
Requirement already satisfied: opentelemetry-sdk>=1.27.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (1.38.0)
Requirement already satisfied: opentelemetry-api>=1.27.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (1.38.0)
Collecting opentelemetry-exporter-otlp>=1.27.0 (from vllm)
  Downloading opentelemetry_exporter_otlp-1.42.1-py3-none-any.whl.metadata (2.4 kB)
Collecting opentelemetry-semantic-conventions-ai>=0.4.1 (from vllm)
  Downloading opentelemetry_semantic_conventions_ai-0.5.1-py3-none-any.whl.metadata (997 bytes)
Collecting numba==0.65.0 (from vllm)
  Downloading numba-0.65.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.9 kB)
INFO: pip is looking at multiple versions of vllm to determine which version is compatible with other requirements. This could take a while.
Collecting vllm
  Downloading vllm-0.20.2-cp38-abi3-manylinux_2_35_x86_64.whl.metadata (10 kB)
  Downloading vllm-0.20.1-1-cp38-abi3-manylinux_2_35_x86_64.whl.metadata (10 kB)
  Downloading vllm-0.20.0-cp38-abi3-manylinux_2_35_x86_64.whl.metadata (10 kB)
  Downloading vllm-0.19.1-cp38-abi3-manylinux_2_31_x86_64.whl.metadata (10 kB)
Collecting outlines_core==0.2.11 (from vllm)
  Downloading outlines_core-0.2.11-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.8 kB)
Collecting numba==0.61.2 (from vllm)
  Downloading numba-0.61.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.8 kB)
Collecting torchaudio==2.10.0 (from vllm)
  Downloading torchaudio-2.10.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (6.9 kB)
Collecting torchvision (from unsloth)
  Downloading torchvision-0.25.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.4 kB)
Collecting flashinfer-python==0.6.6 (from vllm)
  Downloading flashinfer_python-0.6.6-py3-none-any.whl.metadata (11 kB)
Collecting flashinfer-cubin==0.6.6 (from vllm)
  Downloading flashinfer_cubin-0.6.6-py3-none-any.whl.metadata (1.3 kB)
Collecting nvidia-cudnn-frontend<1.19.0,>=1.13.0 (from vllm)
  Downloading nvidia_cudnn_frontend-1.18.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (4.4 kB)
Collecting nvidia-cutlass-dsl>=4.4.0.dev1 (from vllm)
  Downloading nvidia_cutlass_dsl-4.5.2-py3-none-any.whl.metadata (2.8 kB)
Collecting quack-kernels>=0.2.7 (from vllm)
  Downloading quack_kernels-0.4.1-py3-none-any.whl.metadata (640 bytes)
Collecting loguru (from compressed-tensors==0.15.0.1->vllm)
  Downloading loguru-0.7.3-py3-none-any.whl.metadata (22 kB)
Collecting astor (from depyf==0.20.0->vllm)
  Downloading astor-0.8.1-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from depyf==0.20.0->vllm) (0.3.8)
Collecting apache-tvm-ffi!=0.1.8,!=0.1.8.post0,<0.2,>=0.1.6 (from flashinfer-python==0.6.6->vllm)
  Downloading apache_tvm_ffi-0.1.11-cp312-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (6.1 kB)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.6->vllm) (8.4.0)
Requirement already satisfied: nvidia-ml-py in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.6->vllm) (13.595.45)
Requirement already satisfied: tabulate in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.6->vllm) (0.9.0)
Collecting interegular>=0.3.2 (from lm-format-enforcer==0.11.3->vllm)
  Downloading interegular-0.3.3-py37-none-any.whl.metadata (3.0 kB)
Collecting llvmlite<0.45,>=0.44.0dev0 (from numba==0.61.2->vllm)
  Downloading llvmlite-0.44.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.0 kB)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch<2.11.0,>=2.4.0->unsloth) (1.14.0)

In [1]:
import unsloth, trl, transformers, torch
import numpy as np, datasets, vllm

print("unsloth", unsloth.__version__)
print("trl", trl.__version__)
print("transformers", transformers.__version__)
print("torch", torch.__version__)
print("numpy", np.__version__)
print("dataset", datasets.__version__)
print("vllm",vllm.__version__)
print("CUDA tillgänglig:", torch.cuda.is_available())

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
unsloth 2026.5.8
trl 0.24.0
transformers 4.57.6
torch 2.10.0+cu128
numpy 2.0.2
dataset 4.3.0
vllm 0.19.1
CUDA tillgänglig: True

In [2]:
%%bash
# Replace your-username and your-repo-name with your actual GitHub details
BRANCH="runBranch"
USER="huineith"
REPO="AgenticAndRL_LocalMathModels"

# Define the files to download
FILES=("utils.py" "prompts.py" "rewards.py" "grpo_trainer.py" "agent.py" "benchmarker.py" "warmup_data.json" "start_grpo_sub_process.py")

echo "Fetching fresh files from GitHub and overwriting local copies..."
for file in "${FILES[@]}"; do
    wget -q -O "/content/$file" "https://raw.githubusercontent.com/$USER/$REPO/$BRANCH/$file"
    echo " ✓ Updated: $file"
done

Fetching fresh files from GitHub and overwriting local copies...
 ✓ Updated: utils.py
 ✓ Updated: prompts.py
 ✓ Updated: rewards.py
 ✓ Updated: grpo_trainer.py
 ✓ Updated: agent.py
 ✓ Updated: benchmarker.py
 ✓ Updated: warmup_data.json
 ✓ Updated: start_grpo_sub_process.py

In [3]:
# Cell 2 — Mount Google Drive (needed for checkpoint and result saving)
import os
import sys
from google.colab import drive

drive.mount('/content/drive')

CONTENT_DIR = '/content'
os.chdir(CONTENT_DIR)
if CONTENT_DIR not in sys.path:
    sys.path.insert(0, CONTENT_DIR)

print(f'Working directory: {os.getcwd()}')
print('Source files were downloaded from GitHub in the previous cell.')

Mounted at /content/drive
Working directory: /content
Source files were downloaded from GitHub in the previous cell.

In [4]:
# Cell 3 — GPU diagnostics
import torch

if torch.cuda.is_available():
    name  = torch.cuda.get_device_name(0)
    total = torch.cuda.get_device_properties(0).total_memory / 1e9
    free  = (torch.cuda.get_device_properties(0).total_memory - torch.cuda.memory_allocated(0)) / 1e9
    print(f'GPU   : {name}')
    print(f'VRAM  : {total:.1f} GB total  |  {free:.1f} GB free')
    print(f'BF16  : {torch.cuda.is_bf16_supported()}')
else:
    print('WARNING: No GPU detected. Switch runtime to L4 GPU in Runtime > Change runtime type.')

GPU   : NVIDIA A100-SXM4-40GB
VRAM  : 42.4 GB total  |  42.4 GB free
BF16  : True

In [5]:
# Cell 4 — Configuration
MODEL_3B        = 'unsloth/Qwen2.5-3B-Instruct-bnb-4bit'
MODEL_1_5B        = 'unsloth/Qwen2.5-1.5B-Instruct-bnb-4bit'
DATA_FRACTIONS  = [0.025, 0.05, 0.10]
WARMUP_PATH     = 'warmup_data.json'
SEED            = 42
MAX_EPOCHS      = 3

DRIVE_SAVE_DIR  = '/content/drive/MyDrive/ExamensArbete/checkpoints'
BENCHMARK_DIR   = '/content/drive/MyDrive/ExamensArbete/benchmark_results'

print('Config:')
print(f'  3B model       : {MODEL_3B}')
print(f'  1.5B model       : {MODEL_1_5B}')
print(f'  Data fractions : {[int(f*100) for f in DATA_FRACTIONS]}%')
print(f'  Checkpoint dir : {DRIVE_SAVE_DIR}')

Config:
  3B model       : unsloth/Qwen2.5-3B-Instruct-bnb-4bit
  1.5B model       : unsloth/Qwen2.5-1.5B-Instruct-bnb-4bit
  Data fractions : [2, 5, 10]%
  Checkpoint dir : /content/drive/MyDrive/ExamensArbete/checkpoints

## Test Run (optional)

Run the cell below **instead of Cells 5–8** to do a fast end-to-end check of the whole pipeline.
It trains the 3B model on 1% of the data (≈74 examples, 1 epoch) then runs inference on 20 questions.
Total time on an L4 should be under 15 minutes.

If this cell completes without errors the full pipeline is safe to run.

In [ ]:
# Test Cell — end-to-end pipeline check
# Trains 3B on 1% data then runs a 20-question mini benchmark.
# Run Cells 1-4 first so that dependencies are installed and config variables are set.

import gc
import os
import torch
from grpo_trainer import run_grpo
from benchmarker import (
    load_benchmark_questions,
    _load_trained_model,
    _run_nonagentic,
    _format_trained_prompt,
    _compute_metrics,
)
from utils import extract_tagged_answer

TEST_FRACTION    = 0.01   # ~74 training examples
TEST_CHECKPOINT  = f'{DRIVE_SAVE_DIR}/grpo_7b_1pct_best'
TEST_N_QUESTIONS = 20

# ── Step 1: Train ──────────────────────────────────────────────────────────────
print('=' * 60)
print('STEP 1: Training 3B on 1% data (1 epoch max)')
print('=' * 60)

if os.path.exists(TEST_CHECKPOINT):
    print(f'Checkpoint already exists at {TEST_CHECKPOINT} — skipping training.')
else:
    model, tokenizer, best_acc = run_grpo(
        model_name=MODEL_3B,
        data_fraction=TEST_FRACTION,
        save_dir=DRIVE_SAVE_DIR,
        warmup_path=WARMUP_PATH,
        max_epochs=1,   # single epoch keeps the test fast
        seed=SEED,
    )
    del model, tokenizer
    gc.collect()
    torch.cuda.empty_cache()
    print(f'\nTraining complete. Best val accuracy: {best_acc:.4f}')

# ── Step 2: Mini benchmark (non-agentic, 20 questions) ─────────────────────────
print()
print('=' * 60)
print(f'STEP 2: Mini benchmark ({TEST_N_QUESTIONS} questions, 3B no agent)')
print('=' * 60)

questions, solutions = load_benchmark_questions(TEST_N_QUESTIONS, seed=SEED)
model, tokenizer = _load_trained_model(TEST_CHECKPOINT)
results = _run_nonagentic(
    model, tokenizer, questions, solutions,
    _format_trained_prompt, extract_tagged_answer,
)
del model, tokenizer
gc.collect()
torch.cuda.empty_cache()

metrics = _compute_metrics(results)
print(f'\nTest results ({TEST_N_QUESTIONS} questions):')
print(f'  Accuracy   : {metrics["accuracy"]:.2%}  ({metrics["correct"]}/{metrics["total"]})')
print(f'  Avg tokens : {metrics["avg_tokens"]:.0f}')
print()
print('✓ Pipeline completed without errors.')
print('  Note: accuracy will be low at 1% data — that is expected.')
print('  A non-zero accuracy (> 0) means the reward signal is working.')

Unsloth: UnslothBCOTrainer is already patched.
Unsloth: UnslothCPOTrainer is already patched.
Unsloth: UnslothDPOTrainer is already patched.
Unsloth: UnslothGKDTrainer is already patched.
Unsloth: UnslothGRPOTrainer is already patched.
Unsloth: UnslothKTOTrainer is already patched.
Unsloth: UnslothNashMDTrainer is already patched.
Unsloth: UnslothOnlineDPOTrainer is already patched.
Unsloth: UnslothORPOTrainer is already patched.
Unsloth: UnslothPPOTrainer is already patched.
Unsloth: UnslothPRMTrainer is already patched.
Unsloth: UnslothRewardTrainer is already patched.
Unsloth: UnslothRLOOTrainer is already patched.
Unsloth: UnslothSFTTrainer is already patched.
Unsloth: UnslothXPOTrainer is already patched.
============================================================
STEP 1: Training 7B on 1% data (1 epoch max)
============================================================
==((====))==  Unsloth 2026.5.8: Fast Qwen2 patching. Transformers: 4.57.6. vLLM: 0.19.1.
   \\   /|    NVIDIA A100-SXM4-40GB. Num GPUs = 1. Max memory: 39.494 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 8.0. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
unsloth/Qwen2.5-7B-Instruct-bnb-4bit does not have a padding token! Will use pad_token = <|PAD_TOKEN|>.

Unsloth 2026.5.8 patched 28 layers with 28 QKV layers, 28 O layers and 28 MLP layers.

Model: 7b  |  Training examples: 74 (1%)
Validation examples: 100

Unsloth: Tokenizing ["text"] (num_proc=16):   0%|          | 0/25 [00:00<?, ? examples/s]

🦥 Unsloth: Padding-free auto-enabled, enabling faster training.

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 25 | Num Epochs = 1 | Total steps = 7
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 2
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 2 x 1) = 4
 "-____-"     Trainable parameters = 40,370,176 of 7,655,986,688 (0.53% trained)

Unsloth: Will smartly offload gradients to save VRAM!
Unsloth: Double buffering enabled (parallel H2D + compute) for backward pass.

SFT warmup complete -> /content/drive/MyDrive/ExamensArbete/checkpoints/grpo_7b_1pct_warmup

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 74 | Num Epochs = 1 | Total steps = 74
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 4 x 1) = 4
 "-____-"     Trainable parameters = 40,370,176 of 7,655,986,688 (0.53% trained)

Unsloth: Will smartly offload gradients to save VRAM!

Unsloth: Double buffering enabled (parallel H2D + compute) for backward pass.
[Epoch 1] Val accuracy: 0.2800  Best: 0.0000
  -> New best saved to /content/drive/MyDrive/ExamensArbete/checkpoints/grpo_7b_1pct_best
  Metrics saved: /content/drive/MyDrive/ExamensArbete/checkpoints/grpo_7b_1pct_metrics.json
  Plot saved: /content/drive/MyDrive/ExamensArbete/checkpoints/grpo_7b_1pct_metrics.png
GRPO complete. Best val accuracy: 0.2800
Best checkpoint: /content/drive/MyDrive/ExamensArbete/checkpoints/grpo_7b_1pct_best

Training complete. Best val accuracy: 0.2800

============================================================
STEP 2: Mini benchmark (20 questions, 7B no agent)
============================================================
==((====))==  Unsloth 2026.5.8: Fast Qwen2 patching. Transformers: 4.57.6. vLLM: 0.19.1.
   \\   /|    NVIDIA A100-SXM4-40GB. Num GPUs = 1. Max memory: 39.494 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 8.0. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Test results (20 questions):
  Accuracy   : 55.00%  (11/20)
  Avg tokens : 328

✓ Pipeline completed without errors.
  Note: accuracy will be low at 1% data — that is expected.
  A non-zero accuracy (> 0) means the reward signal is working.

## Training

Cells 5 and 6 each run 3 independent GRPO training runs (one per data fraction).
Each run: SFT warmup (1 epoch) → GRPO with early stopping (max 3 epochs).
Checkpoints are saved to Drive after every epoch — safe to resume if the session disconnects.
If a `_best` checkpoint already exists for a run, that run is skipped automatically.

In [7]:
import os
import time
import subprocess

RUNS = [
    (MODEL_3B, 0.025), (MODEL_3B, 0.05), (MODEL_3B, 0.10),
]

for model_name, frac in RUNS:
    size_tag = "3b" if "3B" in model_name else "1.5b"
    pct = frac * 100
    pct_str = str(pct).replace('.', '_') if pct % 1 == 0.5 else str(int(pct))
    expected = f"{DRIVE_SAVE_DIR}/grpo_{size_tag}_{pct_str}pct_best"
    
    if os.path.exists(expected):
        print(f"SKIP  {size_tag} {pct_str}% — checkpoint finns redan")
        continue

    print(f"\n{'='*60}\nSTART {size_tag} {pct_str}%\n{'='*60}", flush=True)

    # GPU-status innan start — visar om minnet redan är upptaget.
    print("--- nvidia-smi (före start) ---", flush=True)
    subprocess.run(
        ["nvidia-smi",
         "--query-gpu=memory.used,memory.total",
         "--format=csv,noheader"],
    )

    # Logga till Drive så att loggen överlever även om kerneln/sessionen dör.
    log_path = f"{DRIVE_SAVE_DIR}/grpo_{size_tag}_{pct_str}pct_run.log"
    with open(log_path, "w") as logf:
        proc = subprocess.Popen(
            ["python", "start_grpo_sub_process.py",
             "--model", model_name,
             "--fraction", str(frac),
             "--save_dir", DRIVE_SAVE_DIR,
             "--max_epochs", str(MAX_EPOCHS),
             "--seed", str(SEED)],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,   # fånga även tracebacks i samma ström
            text=True,
            bufsize=1,                  # radbuffrat
        )
        for line in proc.stdout:        # strömmar rad för rad
            print(line, end="", flush=True)   # syns live i cellen
            logf.write(line)
            logf.flush()                # ligger på Drive direkt
        proc.wait()

    returncode = proc.returncode
    print(f"\nEND   {size_tag} {pct_str}%  (returncode {returncode})", flush=True)
    print(f"  Logg sparad: {log_path}", flush=True)

    if returncode != 0:
        print(f"  VARNING: körningen avslutades med fel — fortsätter till nästa.", flush=True)
        # Tolkning av returkoden:
        #   -9 / 137  = OOM-kill (slut på GPU- eller RAM-minne)
        #   annat     = se tracebacken ovan / i loggfilen
        if returncode in (-9, 137):
            print("  -> Trolig OOM-kill. Minska batch/generations i GRPOConfig.", flush=True)

    # Ge GPU-minnet tid att frigöras helt innan nästa subprocess startar.
    time.sleep(15)

print("\nAlla körningar klara (eller överhoppade).")

============================================================
START 3b 2_5%
============================================================
--- nvidia-smi (före start) ---
🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
Unsloth: UnslothBCOTrainer is already patched.
Unsloth: UnslothCPOTrainer is already patched.
Unsloth: UnslothDPOTrainer is already patched.
Unsloth: UnslothGKDTrainer is already patched.
Unsloth: UnslothGRPOTrainer is already patched.
Unsloth: UnslothKTOTrainer is already patched.
Unsloth: UnslothNashMDTrainer is already patched.
Unsloth: UnslothOnlineDPOTrainer is already patched.
Unsloth: UnslothORPOTrainer is already patched.
Unsloth: UnslothPPOTrainer is already patched.
Unsloth: UnslothPRMTrainer is already patched.
Unsloth: UnslothRewardTrainer is already patched.
Unsloth: UnslothRLOOTrainer is already patched.
Unsloth: UnslothSFTTrainer is already patched.
Unsloth: UnslothXPOTrainer is already patched.
==((====))==  Unsloth 2026.5.8: Fast Qwen2 patching. Transformers: 4.57.6. vLLM: 0.19.1.
   \\   /|    NVIDIA A100-SXM4-40GB. Num GPUs = 1. Max memory: 39.494 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 8.0. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Unsloth 2026.5.8 patched 36 layers with 36 QKV layers, 36 O layers and 36 MLP layers.
unsloth/Qwen2.5-3B-Instruct-bnb-4bit does not have a padding token! Will use pad_token = <|PAD_TOKEN|>.

Generating train split:   0%|          | 0/7473 [00:00<?, ? examples/s]
Generating train split: 100%|██████████| 7473/7473 [00:00<00:00, 441216.69 examples/s]

Generating test split:   0%|          | 0/1319 [00:00<?, ? examples/s]
Generating test split: 100%|██████████| 1319/1319 [00:00<00:00, 286365.08 examples/s]
Model: 3b  |  Training examples: 186 (2%)
Validation examples: 100

Unsloth: Tokenizing ["text"] (num_proc=16):   0%|          | 0/25 [00:00<?, ? examples/s]
Unsloth: Tokenizing ["text"] (num_proc=16):   8%|▊         | 2/25 [00:01<00:14,  1.54 examples/s]
Unsloth: Tokenizing ["text"] (num_proc=16):  16%|█▌        | 4/25 [00:01<00:06,  3.27 examples/s]
Unsloth: Tokenizing ["text"] (num_proc=16):  24%|██▍       | 6/25 [00:01<00:03,  5.16 examples/s]
Unsloth: Tokenizing ["text"] (num_proc=16):  32%|███▏      | 8/25 [00:01<00:02,  6.79 examples/s]
Unsloth: Tokenizing ["text"] (num_proc=16):  40%|████      | 10/25 [00:01<00:01,  8.31 examples/s]
Unsloth: Tokenizing ["text"] (num_proc=16):  56%|█████▌    | 14/25 [00:02<00:01, 10.58 examples/s]
Unsloth: Tokenizing ["text"] (num_proc=16):  72%|███████▏  | 18/25 [00:02<00:00, 14.14 examples/s]
Unsloth: Tokenizing ["text"] (num_proc=16):  80%|████████  | 20/25 [00:02<00:00, 11.56 examples/s]
Unsloth: Tokenizing ["text"] (num_proc=16):  88%|████████▊ | 22/25 [00:02<00:00, 11.36 examples/s]
Unsloth: Tokenizing ["text"] (num_proc=16):  96%|█████████▌| 24/25 [00:03<00:00,  9.83 examples/s]
Unsloth: Tokenizing ["text"] (num_proc=16): 100%|██████████| 25/25 [00:03<00:00,  7.44 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 25 | Num Epochs = 1 | Total steps = 7
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 2
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 2 x 1) = 4
 "-____-"     Trainable parameters = 29,933,568 of 3,115,872,256 (0.96% trained)
🦥 Unsloth: Padding-free auto-enabled, enabling faster training.

  0%|          | 0/7 [00:00<?, ?it/s]
 14%|█▍        | 1/7 [00:09<00:54,  9.09s/it]
 29%|██▊       | 2/7 [00:10<00:22,  4.46s/it]
 43%|████▎     | 3/7 [00:11<00:11,  2.96s/it]
 57%|█████▋    | 4/7 [00:12<00:06,  2.25s/it]
 71%|███████▏  | 5/7 [00:13<00:03,  1.87s/it]


 71%|███████▏  | 5/7 [00:13<00:03,  1.87s/it]
 86%|████████▌ | 6/7 [00:15<00:01,  1.63s/it]
100%|██████████| 7/7 [00:15<00:00,  1.29s/it]


100%|██████████| 7/7 [00:17<00:00,  1.29s/it]
100%|██████████| 7/7 [00:17<00:00,  2.49s/it]
Unsloth: Will smartly offload gradients to save VRAM!
Unsloth: Double buffering enabled (parallel H2D + compute) for backward pass.
{'loss': 3.0159, 'grad_norm': 1.2897428274154663, 'learning_rate': 0.0001, 'epoch': 0.77}
{'train_runtime': 17.4187, 'train_samples_per_second': 1.435, 'train_steps_per_second': 0.402, 'train_loss': 2.6511079583849226, 'epoch': 1.0}
SFT warmup complete -> /content/drive/MyDrive/ExamensArbete/checkpoints/grpo_3b_2pct_warmup

Map:   0%|          | 0/186 [00:00<?, ? examples/s]
Map: 100%|██████████| 186/186 [00:00<00:00, 12719.34 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 186 | Num Epochs = 3 | Total steps = 138
O^O/ \_/ \    Batch size per device = 16 | Gradient accumulation steps = 1
\        /    Data Parallel GPUs = 1 | Total batch size (16 x 1 x 1) = 16
 "-____-"     Trainable parameters = 29,933,568 of 3,115,872,256 (0.96% trained)

  0%|          | 0/138 [00:00<?, ?it/s]
  1%|          | 1/138 [05:04<11:34:13, 304.04s/it]
  1%|▏         | 2/138 [05:33<5:22:28, 142.27s/it]
  2%|▏         | 3/138 [06:00<3:22:34, 90.03s/it]
  3%|▎         | 4/138 [06:25<2:23:35, 64.29s/it]
  4%|▎         | 5/138 [11:02<5:12:11, 140.84s/it]
  4%|▍         | 6/138 [11:20<3:38:12, 99.19s/it]
  5%|▌         | 7/138 [16:15<5:56:03, 163.08s/it]
  6%|▌         | 8/138 [16:27<4:09:34, 115.19s/it]
  7%|▋         | 9/138 [17:36<3:36:00, 100.47s/it]
  7%|▋         | 10/138 [17:52<2:38:44, 74.41s/it]


  7%|▋         | 10/138 [17:52<2:38:44, 74.41s/it]
  8%|▊         | 11/138 [18:09<2:00:32, 56.95s/it]
  9%|▊         | 12/138 [18:26<1:33:59, 44.76s/it]
  9%|▉         | 13/138 [18:37<1:11:47, 34.46s/it]
 10%|█         | 14/138 [18:53<1:00:01, 29.05s/it]
 11%|█         | 15/138 [19:10<52:05, 25.41s/it]
 12%|█▏        | 16/138 [19:25<45:08, 22.20s/it]
 12%|█▏        | 17/138 [19:36<37:49, 18.76s/it]
 13%|█▎        | 18/138 [19:54<37:18, 18.65s/it]
 14%|█▍        | 19/138 [20:19<40:56, 20.64s/it]
 14%|█▍        | 20/138 [21:04<54:55, 27.92s/it]


 14%|█▍        | 20/138 [21:04<54:55, 27.92s/it]
 15%|█▌        | 21/138 [21:23<48:58, 25.12s/it]
 16%|█▌        | 22/138 [21:51<50:18, 26.02s/it]
 17%|█▋        | 23/138 [22:10<45:36, 23.80s/it]
 17%|█▋        | 24/138 [22:30<43:30, 22.90s/it]
 18%|█▊        | 25/138 [22:49<40:31, 21.52s/it]
 19%|█▉        | 26/138 [23:09<39:38, 21.24s/it]
 20%|█▉        | 27/138 [23:32<39:58, 21.60s/it]
 20%|██        | 28/138 [23:58<42:12, 23.02s/it]
 21%|██        | 29/138 [24:25<43:56, 24.19s/it]
 22%|██▏       | 30/138 [24:49<43:35, 24.22s/it]


 22%|██▏       | 30/138 [24:49<43:35, 24.22s/it]
 22%|██▏       | 31/138 [25:08<40:18, 22.61s/it]
 23%|██▎       | 32/138 [25:31<39:57, 22.62s/it]
 24%|██▍       | 33/138 [25:58<42:15, 24.15s/it]
 25%|██▍       | 34/138 [26:26<43:47, 25.26s/it]
 25%|██▌       | 35/138 [26:42<38:13, 22.27s/it]
 26%|██▌       | 36/138 [26:58<34:55, 20.54s/it]
 27%|██▋       | 37/138 [27:14<32:01, 19.03s/it]
 28%|██▊       | 38/138 [27:36<33:30, 20.11s/it]
 28%|██▊       | 39/138 [27:59<34:21, 20.82s/it]
 29%|██▉       | 40/138 [28:12<30:06, 18.43s/it]


 29%|██▉       | 40/138 [28:12<30:06, 18.43s/it]
 30%|██▉       | 41/138 [28:40<34:35, 21.39s/it]
 30%|███       | 42/138 [32:55<2:26:18, 91.44s/it]
 31%|███       | 43/138 [33:13<1:50:04, 69.52s/it]
 32%|███▏      | 44/138 [33:30<1:24:02, 53.65s/it]
 33%|███▎      | 45/138 [33:48<1:06:48, 43.10s/it]
 33%|███▎      | 46/138 [34:13<57:53, 37.76s/it]
 34%|███▍      | 47/138 [45:11<5:39:26, 223.80s/it]
 35%|███▍      | 48/138 [45:39<4:07:32, 165.03s/it]
 36%|███▌      | 49/138 [46:07<3:03:45, 123.88s/it]
 36%|███▌      | 50/138 [46:25<2:14:55, 92.00s/it]


 36%|███▌      | 50/138 [46:25<2:14:55, 92.00s/it]
 37%|███▋      | 51/138 [46:47<1:43:14, 71.20s/it]
 38%|███▊      | 52/138 [47:03<1:17:59, 54.42s/it]
 38%|███▊      | 53/138 [47:15<59:05, 41.72s/it]
 39%|███▉      | 54/138 [47:31<47:52, 34.20s/it]
 40%|███▉      | 55/138 [47:59<44:42, 32.32s/it]
 41%|████      | 56/138 [48:20<39:27, 28.87s/it]
 41%|████▏     | 57/138 [48:36<33:43, 24.98s/it]
 42%|████▏     | 58/138 [48:49<28:38, 21.49s/it]
 43%|████▎     | 59/138 [49:12<28:47, 21.87s/it]
 43%|████▎     | 60/138 [49:45<32:53, 25.30s/it]


 43%|████▎     | 60/138 [49:45<32:53, 25.30s/it]
 44%|████▍     | 61/138 [50:09<31:51, 24.82s/it]
 45%|████▍     | 62/138 [50:24<27:37, 21.80s/it]
 46%|████▌     | 63/138 [50:38<24:19, 19.46s/it]
 46%|████▋     | 64/138 [50:55<23:08, 18.76s/it]
 47%|████▋     | 65/138 [51:13<22:21, 18.37s/it]
 48%|████▊     | 66/138 [51:34<23:16, 19.39s/it]
 49%|████▊     | 67/138 [51:51<22:01, 18.61s/it]
 49%|████▉     | 68/138 [52:09<21:21, 18.31s/it]
 50%|█████     | 69/138 [52:29<21:36, 18.78s/it]
 51%|█████     | 70/138 [52:57<24:35, 21.70s/it]


 51%|█████     | 70/138 [52:57<24:35, 21.70s/it]
 51%|█████▏    | 71/138 [53:27<26:56, 24.13s/it]
 52%|█████▏    | 72/138 [53:47<25:05, 22.81s/it]
 53%|█████▎    | 73/138 [54:08<24:16, 22.40s/it]
 54%|█████▎    | 74/138 [54:33<24:43, 23.17s/it]
 54%|█████▍    | 75/138 [54:52<22:57, 21.87s/it]
 55%|█████▌    | 76/138 [55:04<19:33, 18.92s/it]
 56%|█████▌    | 77/138 [55:27<20:33, 20.22s/it]
 57%|█████▋    | 78/138 [55:55<22:30, 22.51s/it]
 57%|█████▋    | 79/138 [56:20<22:58, 23.37s/it]
 58%|█████▊    | 80/138 [56:41<21:54, 22.66s/it]


 58%|█████▊    | 80/138 [56:41<21:54, 22.66s/it]
 59%|█████▊    | 81/138 [56:58<19:54, 20.95s/it]
 59%|█████▉    | 82/138 [57:18<19:07, 20.50s/it]
 60%|██████    | 83/138 [58:04<25:56, 28.31s/it]
 61%|██████    | 84/138 [58:16<21:06, 23.45s/it]
 62%|██████▏   | 85/138 [58:40<20:39, 23.39s/it]
 62%|██████▏   | 86/138 [59:08<21:29, 24.80s/it]
 63%|██████▎   | 87/138 [59:22<18:17, 21.51s/it]
 64%|██████▍   | 88/138 [59:49<19:23, 23.28s/it]
 64%|██████▍   | 89/138 [1:00:17<20:09, 24.68s/it]
 65%|██████▌   | 90/138 [1:00:39<19:06, 23.89s/it]


 65%|██████▌   | 90/138 [1:00:39<19:06, 23.89s/it]
 66%|██████▌   | 91/138 [1:01:02<18:25, 23.52s/it]
 67%|██████▋   | 92/138 [1:01:35<20:13, 26.39s/it]

Unsloth: Will smartly offload gradients to save VRAM!
Unsloth: Double buffering enabled (parallel H2D + compute) for backward pass.
{'loss': 0.067, 'grad_norm': 0.2500762939453125, 'learning_rate': 1.2857142857142858e-06, 'num_tokens': 49698.0, 'completions/mean_length': 84.8625, 'completions/min_length': 41.5, 'completions/max_length': 184.4, 'completions/clipped_ratio': 0.01875, 'completions/mean_terminated_length': 81.64166793823242, 'completions/min_terminated_length': 41.5, 'completions/max_terminated_length': 158.6, 'rewards/compute_reward/mean': 0.879062494635582, 'rewards/compute_reward/std': 0.9117059230804443, 'reward': 0.879062494635582, 'reward_std': 0.7097043097019196, 'frac_reward_zero_std': 0.225, 'completion_length': 84.8625, 'kl': 0.05164884626865387, 'clip_ratio/low_mean': 0.0, 'clip_ratio/low_min': 0.0, 'clip_ratio/high_mean': 0.0, 'clip_ratio/high_max': 0.0, 'clip_ratio/region_mean': 0.0, 'epoch': 0.22}
{'loss': 0.0169, 'grad_norm': 0.2126786708831787, 'learning_rate': 1.9193548387096773e-06, 'num_tokens': 98191.0, 'completions/mean_length': 80.15625, 'completions/min_length': 42.8, 'completions/max_length': 157.2, 'completions/clipped_ratio': 0.0125, 'completions/mean_terminated_length': 78.36964340209961, 'completions/min_terminated_length': 42.8, 'completions/max_terminated_length': 152.9, 'rewards/compute_reward/mean': 0.8862500011920929, 'rewards/compute_reward/std': 1.0435242474079132, 'reward': 0.8862500011920929, 'reward_std': 0.7457368612289429, 'frac_reward_zero_std': 0.125, 'completion_length': 80.15625, 'kl': 0.0535756703466177, 'clip_ratio/low_mean': 0.0, 'clip_ratio/low_min': 0.0, 'clip_ratio/high_mean': 0.0, 'clip_ratio/high_max': 0.0, 'clip_ratio/region_mean': 0.0, 'epoch': 0.43}
{'loss': 0.0039, 'grad_norm': 0.19193680584430695, 'learning_rate': 1.7580645161290321e-06, 'num_tokens': 147806.0, 'completions/mean_length': 88.39375, 'completions/min_length': 43.4, 'completions/max_length': 204.1, 'completions/clipped_ratio': 0.00625, 'completions/mean_terminated_length': 87.26750030517579, 'completions/min_terminated_length': 43.4, 'completions/max_terminated_length': 195.9, 'rewards/compute_reward/mean': 0.8479910612106323, 'rewards/compute_reward/std': 0.8634288936853409, 'reward': 0.8479910612106323, 'reward_std': 0.5986379444599151, 'frac_reward_zero_std': 0.15, 'completion_length': 88.39375, 'kl': 0.04874256253242493, 'clip_ratio/low_mean': 0.0, 'clip_ratio/low_min': 0.0, 'clip_ratio/high_mean': 0.0, 'clip_ratio/high_max': 0.0, 'clip_ratio/region_mean': 0.0, 'epoch': 0.65}
{'loss': 0.0122, 'grad_norm': 0.2639765441417694, 'learning_rate': 1.596774193548387e-06, 'num_tokens': 197207.0, 'completions/mean_length': 83.73125, 'completions/min_length': 40.8, 'completions/max_length': 183.4, 'completions/clipped_ratio': 0.0125, 'completions/mean_terminated_length': 81.73500061035156, 'completions/min_terminated_length': 40.8, 'completions/max_terminated_length': 164.7, 'rewards/compute_reward/mean': 0.9065625131130218, 'rewards/compute_reward/std': 0.9995862960815429, 'reward': 0.9065625131130218, 'reward_std': 0.6671225845813751, 'frac_reward_zero_std': 0.1, 'completion_length': 83.73125, 'kl': 0.042270540818572046, 'clip_ratio/low_mean': 0.0, 'clip_ratio/low_min': 0.0, 'clip_ratio/high_mean': 0.0, 'clip_ratio/high_max': 0.0, 'clip_ratio/region_mean': 0.0, 'epoch': 0.87}
[Epoch 1] Val accuracy: 0.5200  Best: 0.0000
  -> New best saved to /content/drive/MyDrive/ExamensArbete/checkpoints/grpo_3b_2pct_best
{'loss': 0.0603, 'grad_norm': 0.25619763135910034, 'learning_rate': 1.435483870967742e-06, 'num_tokens': 248987.0, 'completions/mean_length': 92.625, 'completions/min_length': 40.9, 'completions/max_length': 214.5, 'completions/clipped_ratio': 0.03125, 'completions/mean_terminated_length': 87.51416854858398, 'completions/min_terminated_length': 40.9, 'completions/max_terminated_length': 185.6, 'rewards/compute_reward/mean': 0.820907735824585, 'rewards/compute_reward/std': 0.8841070532798767, 'reward': 0.820907735824585, 'reward_std': 0.6724696904420853, 'frac_reward_zero_std': 0.2, 'completion_length': 92.625, 'kl': 0.03531833477318287, 'clip_ratio/low_mean': 0.0, 'clip_ratio/low_min': 0.0, 'clip_ratio/high_mean': 0.0, 'clip_ratio/high_max': 0.0, 'clip_ratio/region_mean': 0.0, 'epoch': 1.09}
{'loss': 0.0404, 'grad_norm': 0.2671556770801544, 'learning_rate': 1.2741935483870967e-06, 'num_tokens': 297133.0, 'completions/mean_length': 81.1875, 'completions/min_length': 41.5, 'completions/max_length': 175.6, 'completions/clipped_ratio': 0.00625, 'completions/mean_terminated_length': 80.08750076293946, 'completions/min_terminated_length': 41.5, 'completions/max_terminated_length': 168.1, 'rewards/compute_reward/mean': 1.048020851612091, 'rewards/compute_reward/std': 0.9670880079269409, 'reward': 1.048020851612091, 'reward_std': 0.709800386428833, 'frac_reward_zero_std': 0.225, 'completion_length': 81.1875, 'kl': 0.03952684197574854, 'clip_ratio/low_mean': 0.0, 'clip_ratio/low_min': 0.0, 'clip_ratio/high_mean': 0.0, 'clip_ratio/high_max': 0.0, 'clip_ratio/region_mean': 0.0, 'epoch': 1.3}
{'loss': 0.0288, 'grad_norm': 0.1346357762813568, 'learning_rate': 1.1129032258064515e-06, 'num_tokens': 345694.0, 'completions/mean_length': 82.78125, 'completions/min_length': 43.1, 'completions/max_length': 172.1, 'completions/clipped_ratio': 0.00625, 'completions/mean_terminated_length': 81.78000030517578, 'completions/min_terminated_length': 43.1, 'completions/max_terminated_length': 166.3, 'rewards/compute_reward/mean': 0.8320982098579407, 'rewards/compute_reward/std': 0.878410342335701, 'reward': 0.8320982098579407, 'reward_std': 0.6366847038269043, 'frac_reward_zero_std': 0.25, 'completion_length': 82.78125, 'kl': 0.033642935752868655, 'clip_ratio/low_mean': 0.0, 'clip_ratio/low_min': 0.0, 'clip_ratio/high_mean': 0.0, 'clip_ratio/high_max': 0.0, 'clip_ratio/region_mean': 0.0, 'epoch': 1.52}
{'loss': 0.0073, 'grad_norm': 0.16364926099777222, 'learning_rate': 9.516129032258064e-07, 'num_tokens': 397962.0, 'completions/mean_length': 97.9, 'completions/min_length': 46.3, 'completions/max_length': 201.5, 'completions/clipped_ratio': 0.0125, 'completions/mean_terminated_length': 95.83333435058594, 'completions/min_terminated_length': 46.3, 'completions/max_terminated_length': 184.3, 'rewards/compute_reward/mean': 1.022187501192093, 'rewards/compute_reward/std': 1.013554835319519, 'reward': 1.022187501192093, 'reward_std': 0.6094392031431198, 'frac_reward_zero_std': 0.275, 'completion_length': 97.9, 'kl': 0.031122149154543876, 'clip_ratio/low_mean': 0.0, 'clip_ratio/low_min': 0.0, 'clip_ratio/high_mean': 0.0, 'clip_ratio/high_max': 0.0, 'clip_ratio/region_mean': 0.0, 'epoch': 1.74}
{'loss': 0.031, 'grad_norm': 0.2596837878227234, 'learning_rate': 7.903225806451612e-07, 'num_tokens': 449870.0, 'completions/mean_length': 93.025, 'completions/min_length': 46.4, 'completions/max_length': 198.4, 'completions/clipped_ratio': 0.025, 'completions/mean_terminated_length': 89.4559539794922, 'completions/min_terminated_length': 46.4, 'completions/max_terminated_length': 184.0, 'rewards/compute_reward/mean': 0.8026041567325592, 'rewards/compute_reward/std': 0.8858120054006576, 'reward': 0.8026041567325592, 'reward_std': 0.6609995752573014, 'frac_reward_zero_std': 0.275, 'completion_length': 93.025, 'kl': 0.029687416926026344, 'clip_ratio/low_mean': 0.0, 'clip_ratio/low_min': 0.0, 'clip_ratio/high_mean': 0.0, 'clip_ratio/high_max': 0.0, 'clip_ratio/region_mean': 0.0, 'epoch': 1.96}
[Epoch 2] Val accuracy: 0.5100  Best: 0.5200
  -> No improvement (1/1)
  -> Early stopping triggered.
{'train_runtime': 4355.9185, 'train_samples_per_second': 0.128, 'train_steps_per_second': 0.032, 'train_loss': 0.02972110162448624, 'num_tokens': 460433.0, 'completions/mean_length': 103.09375, 'completions/min_length': 49.0, 'completions/max_length': 231.0, 'completions/clipped_ratio': 0.03125, 'completions/mean_terminated_length': 98.25833511352539, 'completions/min_terminated_length': 49.0, 'completions/max_terminated_length': 184.0, 'rewards/compute_reward/mean': 0.7015624940395355, 'rewards/compute_reward/std': 0.9352653920650482, 'reward': 0.7015624940395355, 'reward_std': 0.6277441680431366, 'frac_reward_zero_std': 0.25, 'completion_length': 103.09375, 'kl': 0.02388344705104828, 'clip_ratio/low_mean': 0.0, 'clip_ratio/low_min': 0.0, 'clip_ratio/high_mean': 0.0, 'clip_ratio/high_max': 0.0, 'clip_ratio/region_mean': 0.0, 'epoch': 2.0}
 67%|██████▋   | 92/138 [1:12:35<20:13, 26.39s/it]
 67%|██████▋   | 92/138 [1:12:35<36:17, 47.35s/it]

  Metrics saved: /content/drive/MyDrive/ExamensArbete/checkpoints/grpo_3b_2pct_metrics.json
  Plot saved: /content/drive/MyDrive/ExamensArbete/checkpoints/grpo_3b_2pct_metrics.png
GRPO complete. Best val accuracy: 0.5200
Best checkpoint: /content/drive/MyDrive/ExamensArbete/checkpoints/grpo_3b_2pct_best
DONE best_acc=0.5200

END   3b 2_5%  (returncode 0)
  Logg sparad: /content/drive/MyDrive/ExamensArbete/checkpoints/grpo_3b_2_5pct_run.log
SKIP  3b 5% — checkpoint finns redan
SKIP  3b 10% — checkpoint finns redan

Alla körningar klara (eller överhoppade).

In [8]:
import os
import time
import subprocess

RUNS = [
    #(MODEL_1_5B, 0.025),
      (MODEL_1_5B, 0.05), (MODEL_1_5B, 0.10),
]

for model_name, frac in RUNS:
    size_tag = "3b" if "3B" in model_name else "1_5b"
    pct = frac * 100
    pct_str = str(pct_str).replace('.', '_') if pct % 1 == 0.5 else str(int(pct))
    expected = f"{DRIVE_SAVE_DIR}/grpo_{size_tag}_{pct_str}pct_best"

    if os.path.exists(expected):
        print(f"SKIP  {size_tag} {pct_str}% — checkpoint finns redan")
        continue

    print(f"\n{'='*60}\nSTART {size_tag} {pct_str}%\n{'='*60}", flush=True)

    # GPU-status innan start — visar om minnet redan är upptaget.
    print("--- nvidia-smi (före start) ---", flush=True)
    subprocess.run(
        ["nvidia-smi",
         "--query-gpu=memory.used,memory.total",
         "--format=csv,noheader"],
    )

    # Logga till Drive så att loggen överlever även om kerneln/sessionen dör.
    log_path = f"{DRIVE_SAVE_DIR}/grpo_{size_tag}_{pct_str}pct_run.log"
    with open(log_path, "w") as logf:
        proc = subprocess.Popen(
            ["python", "-u", "start_grpo_sub_process.py",
             "--model", model_name,
             "--fraction", str(frac),
             "--save_dir", DRIVE_SAVE_DIR,
             "--max_epochs", str(MAX_EPOCHS),
             "--seed", str(SEED)],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,   # fånga även tracebacks i samma ström
            text=True,
            bufsize=1,                  # radbuffrat
        )
        for line in proc.stdout:        # strömmar rad för rad
            print(line, end="", flush=True)   # syns live i cellen
            logf.write(line)
            logf.flush()                # ligger på Drive direkt
        proc.wait()

    returncode = proc.returncode
    print(f"\nEND   {size_tag} {pct_str}%  (returncode {returncode})", flush=True)
    print(f"  Logg sparad: {log_path}", flush=True)

    if returncode != 0:
        print(f"  VARNING: körningen avslutades med fel — fortsätter till nästa.", flush=True)
        # Tolkning av returkoden:
        #   -9 / 137  = OOM-kill (slut på GPU- eller RAM-minne)
        #   annat     = se tracebacken ovan / i loggfilen
        if returncode in (-9, 137):
            print("  -> Trolig OOM-kill. Minska batch/generations i GRPOConfig.", flush=True)

    # Ge GPU-minnet tid att frigöras helt innan nästa subprocess startar.
    time.sleep(15)

print("\nAlla körningar klara (eller överhoppade).")

SKIP  1_5b 5% — checkpoint finns redan

============================================================
START 1_5b 10%
============================================================
--- nvidia-smi (före start) ---
🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
Unsloth: UnslothBCOTrainer is already patched.
Unsloth: UnslothCPOTrainer is already patched.
Unsloth: UnslothDPOTrainer is already patched.
Unsloth: UnslothGKDTrainer is already patched.
Unsloth: UnslothGRPOTrainer is already patched.
Unsloth: UnslothKTOTrainer is already patched.
Unsloth: UnslothNashMDTrainer is already patched.
Unsloth: UnslothOnlineDPOTrainer is already patched.
Unsloth: UnslothORPOTrainer is already patched.
Unsloth: UnslothPPOTrainer is already patched.
Unsloth: UnslothPRMTrainer is already patched.
Unsloth: UnslothRewardTrainer is already patched.
Unsloth: UnslothRLOOTrainer is already patched.
Unsloth: UnslothSFTTrainer is already patched.
Unsloth: UnslothXPOTrainer is already patched.
==((====))==  Unsloth 2026.5.8: Fast Qwen2 patching. Transformers: 4.57.6. vLLM: 0.19.1.
   \\   /|    NVIDIA A100-SXM4-40GB. Num GPUs = 1. Max memory: 39.494 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.10.0+cu128. CUDA: 8.0. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
unsloth/Qwen2.5-1.5B-Instruct-bnb-4bit does not have a padding token! Will use pad_token = <|PAD_TOKEN|>.
Unsloth 2026.5.8 patched 28 layers with 28 QKV layers, 28 O layers and 28 MLP layers.
Model: 1_5b  |  Training examples: 747 (10%)
Validation examples: 100

Unsloth: Tokenizing ["text"] (num_proc=16):   0%|          | 0/25 [00:00<?, ? examples/s]
Unsloth: Tokenizing ["text"] (num_proc=16):   8%|▊         | 2/25 [00:01<00:15,  1.48 examples/s]
Unsloth: Tokenizing ["text"] (num_proc=16):  16%|█▌        | 4/25 [00:01<00:06,  3.19 examples/s]
Unsloth: Tokenizing ["text"] (num_proc=16):  24%|██▍       | 6/25 [00:01<00:03,  5.04 examples/s]
Unsloth: Tokenizing ["text"] (num_proc=16):  32%|███▏      | 8/25 [00:01<00:02,  6.86 examples/s]
Unsloth: Tokenizing ["text"] (num_proc=16):  40%|████      | 10/25 [00:01<00:01,  8.58 examples/s]
Unsloth: Tokenizing ["text"] (num_proc=16):  48%|████▊     | 12/25 [00:01<00:01, 10.25 examples/s]
Unsloth: Tokenizing ["text"] (num_proc=16):  56%|█████▌    | 14/25 [00:02<00:00, 11.16 examples/s]
Unsloth: Tokenizing ["text"] (num_proc=16):  64%|██████▍   | 16/25 [00:02<00:00, 12.29 examples/s]
Unsloth: Tokenizing ["text"] (num_proc=16):  72%|███████▏  | 18/25 [00:02<00:00, 13.22 examples/s]
Unsloth: Tokenizing ["text"] (num_proc=16):  80%|████████  | 20/25 [00:02<00:00, 10.80 examples/s]
Unsloth: Tokenizing ["text"] (num_proc=16):  88%|████████▊ | 22/25 [00:02<00:00, 10.29 examples/s]
Unsloth: Tokenizing ["text"] (num_proc=16):  96%|█████████▌| 24/25 [00:03<00:00,  9.75 examples/s]
Unsloth: Tokenizing ["text"] (num_proc=16): 100%|██████████| 25/25 [00:03<00:00,  7.25 examples/s]
🦥 Unsloth: Padding-free auto-enabled, enabling faster training.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 25 | Num Epochs = 1 | Total steps = 7
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 2
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 2 x 1) = 4
 "-____-"     Trainable parameters = 18,464,768 of 1,562,179,072 (1.18% trained)

  0%|          | 0/7 [00:00<?, ?it/s]
 14%|█▍        | 1/7 [00:04<00:28,  4.81s/it]
 29%|██▊       | 2/7 [00:05<00:12,  2.51s/it]
 43%|████▎     | 3/7 [00:06<00:07,  1.77s/it]
 57%|█████▋    | 4/7 [00:07<00:04,  1.42s/it]
 71%|███████▏  | 5/7 [00:08<00:02,  1.24s/it]

{'loss': 2.5209, 'grad_norm': 0.8952037692070007, 'learning_rate': 0.0001, 'epoch': 0.77}

 71%|███████▏  | 5/7 [00:08<00:02,  1.24s/it]
 86%|████████▌ | 6/7 [00:09<00:01,  1.12s/it]
100%|██████████| 7/7 [00:09<00:00,  1.11it/s]

{'train_runtime': 11.3486, 'train_samples_per_second': 2.203, 'train_steps_per_second': 0.617, 'train_loss': 2.3005930355616977, 'epoch': 1.0}

100%|██████████| 7/7 [00:11<00:00,  1.11it/s]
100%|██████████| 7/7 [00:11<00:00,  1.62s/it]
SFT warmup complete -> /content/drive/MyDrive/ExamensArbete/checkpoints/grpo_1_5b_10pct_warmup

Map:   0%|          | 0/747 [00:00<?, ? examples/s]
Map: 100%|██████████| 747/747 [00:00<00:00, 19845.10 examples/s]
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 747 | Num Epochs = 3 | Total steps = 558
O^O/ \_/ \    Batch size per device = 16 | Gradient accumulation steps = 1
\        /    Data Parallel GPUs = 1 | Total batch size (16 x 1 x 1) = 16
 "-____-"     Trainable parameters = 18,464,768 of 1,562,179,072 (1.18% trained)

  0%|          | 0/558 [00:00<?, ?it/s]Unsloth: Will smartly offload gradients to save VRAM!

  0%|          | 1/558 [05:07<47:37:27, 307.80s/it]Unsloth: Double buffering enabled (parallel H2D + compute) for backward pass.

  0%|          | 2/558 [05:28<21:27:09, 138.90s/it]
  1%|          | 3/558 [05:49<13:07:42, 85.16s/it]
  1%|          | 4/558 [06:11<9:13:51, 59.98s/it]
  1%|          | 5/558 [06:32<7:05:25, 46.16s/it]
  1%|          | 6/558 [06:54<5:47:37, 37.79s/it]
  1%|▏         | 7/558 [07:15<4:58:23, 32.49s/it]
  1%|▏         | 8/558 [07:30<4:04:25, 26.66s/it]
  2%|▏         | 9/558 [07:50<3:47:25, 24.86s/it]
  2%|▏         | 10/558 [08:05<3:19:14, 21.82s/it]

{'loss': 0.0545, 'grad_norm': 0.1282631903886795, 'learning_rate': 3.2142857142857145e-07, 'num_tokens': 58004.0, 'completions/mean_length': 139.3, 'completions/min_length': 39.0, 'completions/max_length': 237.0, 'completions/clipped_ratio': 0.09375, 'completions/mean_terminated_length': 127.95812683105468, 'completions/min_terminated_length': 39.0, 'completions/max_terminated_length': 223.1, 'rewards/compute_reward/mean': 0.22593750059604645, 'rewards/compute_reward/std': 0.5177634745836258, 'reward': 0.22593750059604645, 'reward_std': 0.3908336669206619, 'frac_reward_zero_std': 0.375, 'completion_length': 139.3, 'kl': 0.12957878485322, 'clip_ratio/low_mean': 0.0, 'clip_ratio/low_min': 0.0, 'clip_ratio/high_mean': 0.0, 'clip_ratio/high_max': 0.0, 'clip_ratio/region_mean': 0.0, 'epoch': 0.05}

  2%|▏         | 10/558 [08:05<3:19:14, 21.82s/it]
  2%|▏         | 11/558 [08:27<3:18:38, 21.79s/it]
  2%|▏         | 12/558 [08:48<3:16:36, 21.61s/it]
  2%|▏         | 13/558 [09:10<3:15:28, 21.52s/it]
  3%|▎         | 14/558 [09:31<3:14:56, 21.50s/it]
  3%|▎         | 15/558 [09:47<2:59:35, 19.84s/it]
  3%|▎         | 16/558 [10:07<2:58:53, 19.80s/it]
  3%|▎         | 17/558 [10:26<2:56:35, 19.58s/it]
  3%|▎         | 18/558 [10:47<3:00:56, 20.11s/it]
  3%|▎         | 19/558 [11:09<3:04:37, 20.55s/it]
  4%|▎         | 20/558 [11:26<2:56:21, 19.67s/it]

{'loss': 0.0341, 'grad_norm': 0.20930595695972443, 'learning_rate': 6.785714285714286e-07, 'num_tokens': 117185.0, 'completions/mean_length': 144.13125, 'completions/min_length': 49.9, 'completions/max_length': 239.5, 'completions/clipped_ratio': 0.125, 'completions/mean_terminated_length': 130.09609832763672, 'completions/min_terminated_length': 49.9, 'completions/max_terminated_length': 223.6, 'rewards/compute_reward/mean': 0.3316666692495346, 'rewards/compute_reward/std': 0.5569576621055603, 'reward': 0.3316666692495346, 'reward_std': 0.4395581752061844, 'frac_reward_zero_std': 0.375, 'completion_length': 144.13125, 'kl': 0.10276354104280472, 'clip_ratio/low_mean': 0.0, 'clip_ratio/low_min': 0.0, 'clip_ratio/high_mean': 0.0, 'clip_ratio/high_max': 0.0, 'clip_ratio/region_mean': 0.0, 'epoch': 0.11}

  4%|▎         | 20/558 [11:26<2:56:21, 19.67s/it]
  4%|▍         | 21/558 [11:48<3:00:46, 20.20s/it]
  4%|▍         | 22/558 [12:09<3:03:32, 20.55s/it]
  4%|▍         | 23/558 [12:23<2:45:08, 18.52s/it]
  4%|▍         | 24/558 [12:44<2:52:17, 19.36s/it]
  4%|▍         | 25/558 [13:05<2:55:45, 19.79s/it]
  5%|▍         | 26/558 [13:26<2:58:38, 20.15s/it]
  5%|▍         | 27/558 [13:48<3:02:14, 20.59s/it]
  5%|▌         | 28/558 [14:09<3:04:07, 20.85s/it]
  5%|▌         | 29/558 [14:31<3:05:29, 21.04s/it]
  5%|▌         | 30/558 [14:52<3:05:56, 21.13s/it]

{'loss': 0.0648, 'grad_norm': 0.1166379302740097, 'learning_rate': 1.0357142857142857e-06, 'num_tokens': 174431.0, 'completions/mean_length': 131.4125, 'completions/min_length': 38.8, 'completions/max_length': 245.8, 'completions/clipped_ratio': 0.10625, 'completions/mean_terminated_length': 116.32097473144532, 'completions/min_terminated_length': 38.8, 'completions/max_terminated_length': 218.3, 'rewards/compute_reward/mean': 0.26041666865348817, 'rewards/compute_reward/std': 0.5520564496517182, 'reward': 0.26041666865348817, 'reward_std': 0.4217542916536331, 'frac_reward_zero_std': 0.425, 'completion_length': 131.4125, 'kl': 0.13240530639886855, 'clip_ratio/low_mean': 0.0, 'clip_ratio/low_min': 0.0, 'clip_ratio/high_mean': 0.0, 'clip_ratio/high_max': 0.0, 'clip_ratio/region_mean': 0.0, 'epoch': 0.16}

  5%|▌         | 30/558 [14:52<3:05:56, 21.13s/it]
  6%|▌         | 31/558 [15:13<3:06:31, 21.24s/it]
  6%|▌         | 32/558 [17:19<7:41:12, 52.61s/it]
  6%|▌         | 33/558 [17:41<6:18:31, 43.26s/it]
  6%|▌         | 34/558 [18:00<5:15:03, 36.08s/it]
  6%|▋         | 35/558 [18:22<4:36:18, 31.70s/it]
  6%|▋         | 36/558 [18:43<4:09:11, 28.64s/it]
  7%|▋         | 37/558 [19:05<3:50:13, 26.51s/it]
  7%|▋         | 38/558 [19:26<3:36:30, 24.98s/it]
  7%|▋         | 39/558 [19:47<3:24:32, 23.65s/it]
  7%|▋         | 40/558 [20:08<3:18:20, 22.97s/it]

{'loss': 0.0862, 'grad_norm': 0.11212364584207535, 'learning_rate': 1.3928571428571427e-06, 'num_tokens': 232782.0, 'completions/mean_length': 140.51875, 'completions/min_length': 40.1, 'completions/max_length': 252.1, 'completions/clipped_ratio': 0.1125, 'completions/mean_terminated_length': 126.12169952392578, 'completions/min_terminated_length': 40.1, 'completions/max_terminated_length': 231.5, 'rewards/compute_reward/mean': 0.26583333164453504, 'rewards/compute_reward/std': 0.46772828996181487, 'reward': 0.26583333164453504, 'reward_std': 0.3827029585838318, 'frac_reward_zero_std': 0.375, 'completion_length': 140.51875, 'kl': 0.11542435735464096, 'clip_ratio/low_mean': 0.0, 'clip_ratio/low_min': 0.0, 'clip_ratio/high_mean': 0.0, 'clip_ratio/high_max': 0.0, 'clip_ratio/region_mean': 0.0, 'epoch': 0.22}

  7%|▋         | 40/558 [20:08<3:18:20, 22.97s/it]
  7%|▋         | 41/558 [20:31<3:18:06, 22.99s/it]
  8%|▊         | 42/558 [20:48<3:02:50, 21.26s/it]
  8%|▊         | 43/558 [21:05<2:52:18, 20.07s/it]
  8%|▊         | 44/558 [21:22<2:43:59, 19.14s/it]
  8%|▊         | 45/558 [21:44<2:49:58, 19.88s/it]
  8%|▊         | 46/558 [22:06<2:53:45, 20.36s/it]
  8%|▊         | 47/558 [22:27<2:56:05, 20.68s/it]
  9%|▊         | 48/558 [22:48<2:57:14, 20.85s/it]
  9%|▉         | 49/558 [23:10<2:58:22, 21.03s/it]
  9%|▉         | 50/558 [23:31<2:58:55, 21.13s/it]

{'loss': 0.0693, 'grad_norm': 0.10928349196910858, 'learning_rate': 1.75e-06, 'num_tokens': 289589.0, 'completions/mean_length': 132.44375, 'completions/min_length': 48.4, 'completions/max_length': 240.3, 'completions/clipped_ratio': 0.09375, 'completions/mean_terminated_length': 120.7125144958496, 'completions/min_terminated_length': 48.4, 'completions/max_terminated_length': 209.3, 'rewards/compute_reward/mean': 0.3364583283662796, 'rewards/compute_reward/std': 0.6326069951057434, 'reward': 0.3364583283662796, 'reward_std': 0.4458245366811752, 'frac_reward_zero_std': 0.425, 'completion_length': 132.44375, 'kl': 0.12511561959981918, 'clip_ratio/low_mean': 0.0, 'clip_ratio/low_min': 0.0, 'clip_ratio/high_mean': 0.0, 'clip_ratio/high_max': 0.0, 'clip_ratio/region_mean': 0.0, 'epoch': 0.27}

  9%|▉         | 50/558 [23:31<2:58:55, 21.13s/it]
  9%|▉         | 51/558 [23:49<2:51:12, 20.26s/it]
  9%|▉         | 52/558 [24:11<2:53:25, 20.57s/it]
  9%|▉         | 53/558 [24:32<2:54:53, 20.78s/it]
 10%|▉         | 54/558 [24:53<2:56:19, 20.99s/it]
 10%|▉         | 55/558 [25:15<2:57:09, 21.13s/it]
 10%|█         | 56/558 [25:36<2:56:51, 21.14s/it]
 10%|█         | 57/558 [25:57<2:57:13, 21.22s/it]
 10%|█         | 58/558 [26:19<2:57:25, 21.29s/it]
 11%|█         | 59/558 [26:40<2:57:24, 21.33s/it]
 11%|█         | 60/558 [27:02<2:57:16, 21.36s/it]

{'loss': 0.0454, 'grad_norm': 0.12118863314390182, 'learning_rate': 1.9880478087649403e-06, 'num_tokens': 346417.0, 'completions/mean_length': 134.525, 'completions/min_length': 47.5, 'completions/max_length': 252.2, 'completions/clipped_ratio': 0.1, 'completions/mean_terminated_length': 121.20172958374023, 'completions/min_terminated_length': 47.5, 'completions/max_terminated_length': 214.0, 'rewards/compute_reward/mean': 0.4703125, 'rewards/compute_reward/std': 0.7424138844013214, 'reward': 0.4703125059604645, 'reward_std': 0.5651792198419571, 'frac_reward_zero_std': 0.3, 'completion_length': 134.525, 'kl': 0.11936277821660042, 'clip_ratio/low_mean': 0.0, 'clip_ratio/low_min': 0.0, 'clip_ratio/high_mean': 0.0, 'clip_ratio/high_max': 0.0, 'clip_ratio/region_mean': 0.0, 'epoch': 0.32}

 11%|█         | 60/558 [27:02<2:57:16, 21.36s/it]
 11%|█         | 61/558 [27:23<2:57:12, 21.39s/it]
 11%|█         | 62/558 [27:40<2:46:46, 20.17s/it]
 11%|█▏        | 63/558 [28:02<2:49:29, 20.54s/it]
 11%|█▏        | 64/558 [28:23<2:51:02, 20.77s/it]
 12%|█▏        | 65/558 [28:44<2:51:26, 20.86s/it]
 12%|█▏        | 66/558 [29:06<2:52:26, 21.03s/it]
 12%|█▏        | 67/558 [29:27<2:52:54, 21.13s/it]
 12%|█▏        | 68/558 [29:48<2:53:12, 21.21s/it]
 12%|█▏        | 69/558 [30:10<2:53:18, 21.26s/it]
 13%|█▎        | 70/558 [30:31<2:53:11, 21.29s/it]

{'loss': 0.0691, 'grad_norm': 0.0968141257762909, 'learning_rate': 1.948207171314741e-06, 'num_tokens': 404293.0, 'completions/mean_length': 134.7, 'completions/min_length': 48.6, 'completions/max_length': 250.9, 'completions/clipped_ratio': 0.10625, 'completions/mean_terminated_length': 120.76360931396485, 'completions/min_terminated_length': 48.6, 'completions/max_terminated_length': 210.7, 'rewards/compute_reward/mean': 0.3744791686534882, 'rewards/compute_reward/std': 0.6942579954862594, 'reward': 0.3744791686534882, 'reward_std': 0.4763497292995453, 'frac_reward_zero_std': 0.375, 'completion_length': 134.7, 'kl': 0.1175602450966835, 'clip_ratio/low_mean': 0.0, 'clip_ratio/low_min': 0.0, 'clip_ratio/high_mean': 0.0, 'clip_ratio/high_max': 0.0, 'clip_ratio/region_mean': 0.0, 'epoch': 0.38}

 13%|█▎        | 70/558 [30:31<2:53:11, 21.29s/it]
 13%|█▎        | 71/558 [30:53<2:53:32, 21.38s/it]
 13%|█▎        | 72/558 [31:14<2:53:12, 21.38s/it]
 13%|█▎        | 73/558 [31:35<2:51:06, 21.17s/it]
 13%|█▎        | 74/558 [31:56<2:51:21, 21.24s/it]
 13%|█▎        | 75/558 [32:18<2:51:56, 21.36s/it]
 14%|█▎        | 76/558 [32:39<2:51:51, 21.39s/it]
 14%|█▍        | 77/558 [32:57<2:42:22, 20.25s/it]
 14%|█▍        | 78/558 [33:13<2:33:04, 19.13s/it]
 14%|█▍        | 79/558 [33:35<2:38:20, 19.83s/it]
 14%|█▍        | 80/558 [33:56<2:41:50, 20.32s/it]

{'loss': 0.037, 'grad_norm': 0.14982526004314423, 'learning_rate': 1.908366533864542e-06, 'num_tokens': 460264.0, 'completions/mean_length': 129.79375, 'completions/min_length': 35.8, 'completions/max_length': 244.1, 'completions/clipped_ratio': 0.08125, 'completions/mean_terminated_length': 118.94753189086914, 'completions/min_terminated_length': 35.8, 'completions/max_terminated_length': 224.1, 'rewards/compute_reward/mean': 0.36052083373069765, 'rewards/compute_reward/std': 0.5902434885501862, 'reward': 0.36052082777023314, 'reward_std': 0.44556133449077606, 'frac_reward_zero_std': 0.35, 'completion_length': 129.79375, 'kl': 0.15485746562480926, 'clip_ratio/low_mean': 0.0, 'clip_ratio/low_min': 0.0, 'clip_ratio/high_mean': 0.0, 'clip_ratio/high_max': 0.0, 'clip_ratio/region_mean': 0.0, 'epoch': 0.43}

 14%|█▍        | 80/558 [33:56<2:41:50, 20.32s/it]
 15%|█▍        | 81/558 [34:19<2:46:59, 21.01s/it]
 15%|█▍        | 82/558 [34:39<2:44:19, 20.71s/it]
 15%|█▍        | 83/558 [35:00<2:45:36, 20.92s/it]
 15%|█▌        | 84/558 [35:18<2:37:15, 19.91s/it]
 15%|█▌        | 85/558 [35:39<2:40:00, 20.30s/it]
 15%|█▌        | 86/558 [35:59<2:38:41, 20.17s/it]
 16%|█▌        | 87/558 [36:20<2:41:12, 20.54s/it]
 16%|█▌        | 88/558 [36:42<2:42:47, 20.78s/it]
 16%|█▌        | 89/558 [37:03<2:43:46, 20.95s/it]
 16%|█▌        | 90/558 [37:25<2:44:39, 21.11s/it]

{'loss': 0.0291, 'grad_norm': 0.1578664481639862, 'learning_rate': 1.8685258964143424e-06, 'num_tokens': 516516.0, 'completions/mean_length': 129.575, 'completions/min_length': 41.7, 'completions/max_length': 247.9, 'completions/clipped_ratio': 0.06875, 'completions/mean_terminated_length': 119.81000366210938, 'completions/min_terminated_length': 41.7, 'completions/max_terminated_length': 205.9, 'rewards/compute_reward/mean': 0.5004166692495347, 'rewards/compute_reward/std': 0.7426141798496246, 'reward': 0.5004166692495347, 'reward_std': 0.5264620453119278, 'frac_reward_zero_std': 0.325, 'completion_length': 129.575, 'kl': 0.12368579655885696, 'clip_ratio/low_mean': 0.0, 'clip_ratio/low_min': 0.0, 'clip_ratio/high_mean': 0.0, 'clip_ratio/high_max': 0.0, 'clip_ratio/region_mean': 0.0, 'epoch': 0.48}

 16%|█▌        | 90/558 [37:25<2:44:39, 21.11s/it]
 16%|█▋        | 91/558 [37:48<2:50:11, 21.87s/it]
 16%|█▋        | 92/558 [38:10<2:48:35, 21.71s/it]
 17%|█▋        | 93/558 [38:31<2:47:31, 21.62s/it]
 17%|█▋        | 94/558 [38:52<2:46:42, 21.56s/it]
 17%|█▋        | 95/558 [39:11<2:39:39, 20.69s/it]
 17%|█▋        | 96/558 [39:32<2:40:03, 20.79s/it]
 17%|█▋        | 97/558 [39:56<2:45:59, 21.60s/it]
 18%|█▊        | 98/558 [40:17<2:45:06, 21.54s/it]
 18%|█▊        | 99/558 [40:38<2:43:56, 21.43s/it]
 18%|█▊        | 100/558 [40:56<2:35:45, 20.41s/it]

{'loss': 0.0517, 'grad_norm': 0.1525421440601349, 'learning_rate': 1.8286852589641434e-06, 'num_tokens': 572564.0, 'completions/mean_length': 123.925, 'completions/min_length': 38.3, 'completions/max_length': 248.4, 'completions/clipped_ratio': 0.0875, 'completions/mean_terminated_length': 111.94798126220704, 'completions/min_terminated_length': 38.3, 'completions/max_terminated_length': 211.5, 'rewards/compute_reward/mean': 0.4973958283662796, 'rewards/compute_reward/std': 0.7381313443183899, 'reward': 0.4973958283662796, 'reward_std': 0.505610765516758, 'frac_reward_zero_std': 0.325, 'completion_length': 123.925, 'kl': 0.15263379216194153, 'clip_ratio/low_mean': 0.0, 'clip_ratio/low_min': 0.0, 'clip_ratio/high_mean': 0.0, 'clip_ratio/high_max': 0.0, 'clip_ratio/region_mean': 0.0, 'epoch': 0.54}

 18%|█▊        | 100/558 [40:56<2:35:45, 20.41s/it]
 18%|█▊        | 101/558 [41:18<2:37:43, 20.71s/it]
 18%|█▊        | 102/558 [41:39<2:38:39, 20.88s/it]
 18%|█▊        | 103/558 [42:01<2:40:37, 21.18s/it]
 19%|█▊        | 104/558 [42:22<2:41:13, 21.31s/it]
 19%|█▉        | 105/558 [42:41<2:35:53, 20.65s/it]
 19%|█▉        | 106/558 [43:03<2:37:57, 20.97s/it]
 19%|█▉        | 107/558 [43:26<2:41:41, 21.51s/it]
 19%|█▉        | 108/558 [43:42<2:29:47, 19.97s/it]
 20%|█▉        | 109/558 [44:04<2:32:40, 20.40s/it]
 20%|█▉        | 110/558 [44:20<2:23:44, 19.25s/it]


:

## Benchmark

Uses the 40% checkpoint for Groups 1-4. Group 5 is the zero-shot Qwen2.5-14B-Instruct baseline.
500 questions from the official GSM8K test split (fixed seed = 42).

In [ ]:
# Cell 7 — Verify all required checkpoints exist
import os

to_check = {
    '3B 2.5%': f'{DRIVE_SAVE_DIR}/grpo_3b_2_5pct_best',
    '3B 5%': f'{DRIVE_SAVE_DIR}/grpo_3b_5pct_best',
    '3B 10%': f'{DRIVE_SAVE_DIR}/grpo_3b_10pct_best',
    '1.5B 2.5%': f'{DRIVE_SAVE_DIR}/grpo_1_5b_2_5pct_best',
    '1.5B 5%': f'{DRIVE_SAVE_DIR}/grpo_1_5b_5pct_best',
    '1.5B 1+%': f'{DRIVE_SAVE_DIR}/grpo_1_5b_10pct_best',
}

all_ok = True
for label, path in to_check.items():
    status = 'OK     ' if os.path.exists(path) else 'MISSING'
    print(f'  [{status}]  {label}  ->  {path}')
    if 'MISSING' in status:
        all_ok = False

print()
if all_ok:
    print('All checkpoints present. Ready to run benchmark.')
else:
    print('Some checkpoints are missing. Complete training before running the benchmark.')

In [ ]:
# Cell 7a — Configuration & 2-Question Sanity Test Run
import os
from benchmarker import run_h0_benchmark, run_h1_benchmark, run_h2_benchmark

# 1. Define Paths to Checkpoints (Adjust these to your actual Drive structure)
CHECKPOINTS_H1 = {
    "1_5b_2pct":  f"{DRIVE_SAVE_DIR}/grpo_1_5b_2pct_best",
    "1_5b_5pct":  f"{DRIVE_SAVE_DIR}/grpo_1_5b_5pct_best",
    "1_5b_10pct": f"{DRIVE_SAVE_DIR}/grpo_1_5b_10pct_best",
    "3b_2pct":    f"{DRIVE_SAVE_DIR}/grpo_3b_2pct_best",
    "3b_5pct":    f"{DRIVE_SAVE_DIR}/grpo_3b_5pct_best",
    "3b_10pct":   f"{DRIVE_SAVE_DIR}/grpo_3b_10pct_best",
}

# Default choice for Agentic Compute loop evaluation (H2)
AGENT_CHECKPOINT_H2 = CHECKPOINTS_H1["3b_10pct"]

# Setup evaluation directory
TEST_BENCHMARK_DIR = os.path.join(BENCHMARK_DIR, "test_run")

print("=" * 70)
print("LAUNCHING 2-QUESTION SANITY CHECK FOR ALL EVALUATION HYPOTHESES")
print("=" * 70)

# Run H0 Baseline Quick Check
print("\n--- Testing Hypothesis 0 (Untrained Models) ---")
h0_test_metrics = run_h0_benchmark(
    save_dir=TEST_BENCHMARK_DIR,
    n_questions=2,
    seed=SEED
)

# Run H1 Scale & Data Efficiency Quick Check
print("\n--- Testing Hypothesis 1 (GRPO No-Agent Checkpoints) ---")
h1_test_metrics = run_h1_benchmark(
    checkpoints=CHECKPOINTS_H1,
    save_dir=TEST_BENCHMARK_DIR,
    n_questions=2,
    seed=SEED
)

# Run H2 Agentic vs SOTA Quick Check
print("\n--- Testing Hypothesis 2 (Agentic Process + Math Baseline) ---")
h2_test_metrics = run_h2_benchmark(
    agent_checkpoint=AGENT_CHECKPOINT_H2,
    save_dir=TEST_BENCHMARK_DIR,
    n_questions=2,
    seed=SEED,
    skip_baseline=False
)

print("\n" + "=" * 70)
print("SUCCESS: 2-Question test runs completed without sub-process failures.")
print("=" * 70)

In [ ]:
# Cell 9 — Display results table and plot
import pandas as pd
from IPython.display import Image, display

df = pd.read_csv(f'{BENCHMARK_DIR}/benchmark_summary.csv')
df['accuracy_%']         = (df['accuracy'] * 100).round(2)
df['avg_tokens']         = df['avg_tokens'].round(1)
df['tokens_per_correct'] = df['tokens_per_correct'].round(1)

display(df[['group_name', 'accuracy_%', 'avg_tokens', 'tokens_per_correct', 'correct', 'total']])

print()
display(Image(filename=f'{BENCHMARK_DIR}/benchmark_plot.png'))